server.port : 9000

weather:
  loader:
    url: http://localhost:8080/api/v1/weather

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints.web:
    exposure.include: '*'
    base-path: /actuator
  endpoint:
    prometheus.enabled: true
    metrics.enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      loader-latest-circuit-breaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
        ignoreExceptions:
          - ar.edu.unq.weather.metric.domain.exceptions.NotFoundException
          - ar.edu.unq.weather.metric.domain.exceptions.InfoBaeBadRequestError
      loader-list-circuit-breaker:
        registerHealthIndicator: true
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 6
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 4s
        failureRateThreshold: 60
        ignoreExceptions:
          - ar.edu.unq.weather.metric.domain.exceptions.NotFoundException
          - ar.edu.unq.weather.metric.domain.exceptions.InfoBaeBadRequestError
  retry:
    instances:
      loader-latest-retry:
        registerHealthIndicator: true
        maxRetryAttempts: 1
        waitDuration: 20ms
        retryExceptions:
          - java.net.SocketTimeoutException
          - org.springframework.web.client.RestClientException
          - ar.edu.unq.weather.metric.domain.exceptions.InfoBaeInternalServerError
      loader-list-retry:
        registerHealthIndicator: true
        maxRetryAttempts: 2
        waitDuration: 200ms
        retryExceptions:
          - java.net.SocketTimeoutException
          - org.springframework.web.client.RestClientException
          - ar.edu.unq.weather.metric.domain.exceptions.InfoBaeInternalServerError
  bulkhead:
    instances:
      loader-list-bulkhead:
        maxConcurrentCalls: 100
        maxWaitDuration: 100ms
      loader-latest-bulkhead:
        maxConcurrentCalls: 20
        maxWaitDuration: 100ms
  ratelimiter:
    metrics.enabled: true
    instances:
      loader-latest-rate:
        register-health-indicator: true
        limit-for-period: 1000
        limit-refresh-period: 2s
        timeout-duration: 100ms
spring:
  application:
    name: metric-infobae-service
  zipkin:
    baseUrl: http://localhost:9411
  jackson.serialization.indent_output: true

springdoc:
  swagger-ui:
    path: /